#!/bin/bash

# TODO: enter using command line.
KFBO_NUM_TESTS=10
KFBO_TEST_TO_RUN="coreos.ignition.v2.once"

KFBO_KOLA_PATH="/home/$USER/go/bin/kola"
KFBO_QEMU_IMAGE="./coreos_production_image.bin"

echo "kfbo: kola running $KFBO_NUM_TESTS iterations of test $KFBO_TEST_TO_RUN..."

for i in `seq 1 $KFBO_NUM_TESTS`;
do
	$KFBO_KOLA_PATH run -p qemu $KFBO_TEST_TO_RUN --qemu-image $KFBO_QEMU_IMAGE
done

echo "kfbo: done running sequential tests."
