#!/bin/bash

# Run several tests as child processes. Would not recommend specifying more than
# 10 tests to run locally in parallel (due to memory, and storage constraints
# in /tmp).
# KFBO <=> KOLA_FIND_BAD_OUTPUT

# TODO: enter using command line.
KFBO_OUTPUT_NUM_TESTS=5
KFBO_TEST_TO_RUN="coreos.ignition.v2.once"

KFBO_KOLA_PATH="/home/$USER/go/bin/kola"
KFBO_QEMU_IMAGE="./coreos_production_image_old.bin"

echo "kfbo: kola running $KFBO_OUTPUT_NUM_TESTS processes of test $KFBO_TEST_TO_RUN..."

for i in `seq 1 $KFBO_OUTPUT_NUM_TESTS`;
do
	$KFBO_KOLA_PATH run -p qemu $KFBO_TEST_TO_RUN --qemu-image $KFBO_QEMU_IMAGE &
	pids[${i}]=$!
done

for pid in ${pids[*]}; do
	echo "kfbo: waiting for process $pid to exit..."
	wait $pid
done

echo "kfbo: done running parallel tests."
